export enum Slots {
    inventory = 46,
    chest = 63,
    large_chest = 90,
    crafting_table = 46,
    furnace = 39,
    blast_furnace = 39,
    smoker = 39,
    dispenser = 45,
    enchantment_table = 38,
    brewing_stand = 41,
    villager_tading = 38,
    beacon = 36,
    anvil = 38,
    hopper = 41,
    shulker_box = 63,
    horse = 37,
    cartography_table = 39,
    drindstone = 39,
    loom = 40,
    stonecutter = 38,
    smithing_table = 40,
}